# Generated by Django 3.1.2 on 2020-11-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_auto_20201101_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='file',
            field=models.FileField(upload_to='translation'),
        ),
    ]
